### ISSUE TITLE
attributes not supported, e.g. avgspeed

### ISSUE THREAD

**Issue by swissembedded** [GIScience/openrouteservice-py#10]
Mssing feature, attributes are not supported yet.
https://openrouteservice.org/documentation/#/reference/directions/directions/directions-service

**Comment by nilsnolde** [comment]
Yep, it's commented out in the code. No idea why I did that back then.. It'll be implemented this week! I'm on vacation for longer time, but I know someone who can take care of this.

**Comment by nilsnolde** [comment]
Also done, thx to @isikl
