### ISSUE TITLE
Directions API, issue with parameters set to false

### ISSUE THREAD

**Issue by JeromeHoen** [GIScience/openrouteservice-py#28]
Hello!

There is an issue with boolean parameters that you convert to string. You only stringify them if they are True, for instance, see line 199 of the file directions.py:

    if instructions:
        # not checked on backend, check here
        params["instructions"] = convert._convert_bool(instructions)

But as I want to set it to false, it doesn't get converted to string and the instructions are still in the response. Please consider reviewing all the boolean parameters that need a conversion.

PS: the hot fix is setting the parameters to "false" as a string.

**Comment by nilsnolde** [comment]
Good point, thx! I'll have a look at the PR and fix asap.
