### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by RafaelAbel** [GIScience/openrouteservice-py#32]
Installtion with pip and conda don't work.

Installing collected packages: certifi, requests, openrouteservice
  Found existing installation: certifi 2018.11.29
Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

For conda install the chanel nilsnolde cannot be found.

My setup:
win64
conda 4.5.12

**Comment by nilsnolde** [comment]
Yes, you're right. My current dependency management is a load of s***..

Really sorry for that. I'll provide a hot fix later today!

**Comment by nilsnolde** [comment]
OK, this is fixed and tested. `conda` package only available for 2.7, 3.6 and 3.7, due to some conflicts in `responses` package.

Please try again @RafaelAbel and re-open if it didn't work..
