### ISSUE TITLE
ORS TOOL-QGIS ISSUE

### ISSUE THREAD

**Issue by kkrani2009** [GIScience/openrouteservice-py#36]
AttributeError: 'NoneType' object has no attribute 'encode'
https://api.openrouteservice.org/directions?coordinates=85.825409%2C20.25978%7C85.825981%2C20.2564&format=geojson&geometry=true&geometry_format=geojson&id=None&instructions=false&preference=fastest&profile=driving-car

**Comment by nilsnolde** [comment]
Wrong repository
