### ISSUE TITLE
priority field is not supported for optimization api?

### ISSUE THREAD

**Issue by stefanocudini** [GIScience/openrouteservice-py#39]
hi
 I would like to solve jobs that have a higher amount than the others before the others ..
I thought about adding the priority field to get this 

my case study is it:
```python

...vehicles...

jobs = []
for idx, cc in enumerate(job_locs):
    loc = list(reversed(cc))
    amount = random.randrange(1, 5) # random  value for testing..
    jobs.append(ors.optimization.Job(
        id = idx,
        location = cc,
        amount = [amount],
        priority = amount
    ))

clientVrp = ors.Client(base_url='http://myvroom/', key='')
optimized = clientVrp.optimization(
    vehicles = vehicles,
    jobs = jobs,
    geometry = True
)
```

I receive this error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-94-5e80af05f327> in <module>
     41         #amount = [2] # Quantita' contenuto nel Bidone
     42         amount = [amount],
---> 43         priority = amount
     44     ))
     45     folium.Marker(loc, tooltip=folium.Tooltip(amount,permanent=True), icon=folium.Icon(icon='archive', prefix='fa', color='green')).add_to(m)

TypeError: __init__() got an unexpected keyword argument 'priority'
```

**Comment by nilsnolde** [comment]
Thanks for the report. Right, I didn't keep up with vroom's last version. Either you PR it in if you want, or I'll do it at some point myself.

Also ORS alternative routes, round trip & skipped points are not implemented yet.

**Comment by nilsnolde** [comment]
As a workaround you can pass the parameters directly to the request function. Our backend does recognize these parameters since vroom is running on the latest version there. Or if you have your own vroom running, it will also work.

Somewhat similar to the last code snippet in this example:
https://github.com/GIScience/openrouteservice-py#local-ors-instance

**Comment by stefanocudini** [comment]
using client.request(...)  can I pass directly a list of ors.optimization.Job(...)?

**Comment by nilsnolde** [comment]
Just have a look at the `Client.request()` function. You can see for yourself: no code parsing any objects. You'll have to provide a dictionary to `post_json` which mimicks exactly what ORS backend is expecting on arguments, no convenience methods available there.
