### ISSUE TITLE
Missing options argument from API

### ISSUE THREAD

**Issue by Aaron-JE** [GIScience/openrouteservice-py#44]
#### Here's what I did

I have a working script to retrive ischrones. I want to avoid highways, so I added the option like this:
params_iso = {"locations":[[8.681495,49.41461],[8.686507,49.41943]],"range":[300,200],"options":{"avoid_features":["highways"]}}

The locations being added later
---
#### Here's what I got

TypeError: isochrones() got an unexpected keyword argument 'options'---
#### Here's what I was expecting
For the option parameter to work like the api

---
#### Here's what I think could be improved
Adding the options argument

**Comment by Aaron-JE** [comment]
I send post request with the "options" parameter to avoid highways but it throws "unknown keyword" error. I think that functionality if missing, dont know if by desing or bugs

**Comment by nilsnolde** [comment]
You know about the "Edit" button for comments? The template is not for fun..

What `options` do you use? Without explicit examples we can't tell anything.

**Comment by Aaron-JE** [comment]
Sorry, didn't see it nor knew it
