### ISSUE TITLE
Transit API

### ISSUE THREAD

**Issue by KavinduZoysa** [GIScience/openrouteservice-py#46]
Is there any API in openrouteservice, which is equivalent to google transit API? 

I am a new person to this area, so really appreciate your inputs on my question.

**Comment by nilsnolde** [comment]
Please follow the issue template, in which case you wouldn't open this issue. Also please don't cross-post on the forum AND in the repositories.

**Comment by KavinduZoysa** [comment]
I got to know about the forum AFTER I created the issue. Anyway sorry for the inconvenience.
