### ISSUE TITLE
optimization method hidden in development branch

### ISSUE THREAD

**Issue by stefanocudini** [GIScience/openrouteservice-py#47]
I had used this code in version 2.3.0

now doing tests from branch development I find some problems

has changed api di ors-py? for optimixzation request?

```python
import openrouteservice as ors

jobs = []
jobs.append(ors.optimization.Job(
        id = idx,
        location = cc,
        pickup = [1],
    ))
```
```
module 'openrouteservice' has no attribute 'optimization'
```

**Comment by nilsnolde** [comment]
don't use `development` branch. look at the timestamps, it's old. `master` is the truth.
