### ISSUE TITLE
Integrate best practices

### ISSUE THREAD

**Issue by MichaelsJP** [GIScience/openrouteservice-py#59]
- [x] Decent package manager: Poetry
- [x] Good testing eninge: tox
- [x] Code formatting/linting/pep8 check: pre-commit with addons.

**Comment by TheGreatRefrigerator** [comment]
Not sure how the changelog is handled currently and how it works together with pypi.
But there are no entries for the latest releases.
Maybe similar style as in ors backend repo, with linking.
(no pressure, this is only here for completion ;), i'm happy that there are more people to integrate best practices)
